openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /code:
    post:
      operationId: postCode
      responses:
        "202":
          description: Accepted
